package com.aismartmeasure.app.util

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.aismartmeasure.app.data.Measurement
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Locale

/**
 * Generates and shares measurement reports.
 */
object ReportGenerator {

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())

    fun shareReport(context: Context, measurement: Measurement) {
        val timestamp = dateFormat.format(measurement.timestamp)
        val fileName = "AI_Smart_Measure_${System.currentTimeMillis()}.txt"

        val reportContent = buildReport(measurement, timestamp)
        val shareSummary = buildSummary(measurement, timestamp)

        try {
            // Write report file
            val file = File(context.cacheDir, fileName)
            FileOutputStream(file).use { stream ->
                stream.write(reportContent.toByteArray(Charsets.UTF_8))
                stream.flush()
            }

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            // Create share intent
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "AI Smart Measure - 3D Dimensions")
                putExtra(Intent.EXTRA_TEXT, shareSummary)
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(intent, "Share Measurement Report"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun buildReport(m: Measurement, timestamp: String): String {
        return """
            |╔══════════════════════════════════════╗
            |║      AI SMART MEASURE REPORT         ║
            |╠══════════════════════════════════════╣
            |║ Date: $timestamp
            |╠══════════════════════════════════════╣
            |║ DIMENSIONS                           ║
            |╠──────────────────────────────────────╣
            |║ Length: ${formatDimension(m.length)}
            |║ Width:  ${formatDimension(m.width)}
            |║ Height: ${formatDimension(m.height)}
            |╠──────────────────────────────────────╣
            |║ CALCULATED VOLUME                    ║
            |╠──────────────────────────────────────╣
            |║ Volume: ${formatVolume(m.volume)}
            |╚══════════════════════════════════════╝
            |
            |Generated by AI Smart Measure App
        """.trimMargin()
    }

    private fun buildSummary(m: Measurement, timestamp: String): String {
        return """
            |📦 AI Smart Measure Report
            |📅 $timestamp
            |
            |📏 Dimensions:
            |• Length: ${formatDimension(m.length)}
            |• Width: ${formatDimension(m.width)}
            |• Height: ${formatDimension(m.height)}
            |
            |📊 Volume: ${formatVolume(m.volume)}
        """.trimMargin()
    }

    private fun formatDimension(value: Float): String {
        return if (value > 0) String.format(Locale.US, "%.2f m (%.1f cm)", value, value * 100)
        else "Not measured"
    }

    private fun formatVolume(value: Float): String {
        return if (value > 0) String.format(Locale.US, "%.4f m³", value)
        else "Not available"
    }
}
