package com.example.sizecalc

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object ReportGenerator {

    fun generateAndShareReport(context: Context, length: Float, width: Float, height: Float) {
        val dateStr = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())
        val fileName = "3D_Dimension_Report_${System.currentTimeMillis()}.txt"
        val volume = length * width * height
        
        val reportContent = """
            3D SIZE CALCULATOR REPORT
            -------------------------
            Date: $dateStr
            
            OBJECT DIMENSIONS:
            Length: ${String.format(Locale.US, "%.2f", length)} meters
            Width:  ${String.format(Locale.US, "%.2f", width)} meters
            Height: ${String.format(Locale.US, "%.2f", height)} meters
            
            CALCULATED VOLUME:
            Volume: ${String.format(Locale.US, "%.4f", volume)} cubic meters
            
            Generated by 3DSizeCalc App
        """.trimIndent()

        try {
            val file = File(context.cacheDir, fileName)
            FileOutputStream(file).use { outputStream ->
                outputStream.write(reportContent.toByteArray()) 
                outputStream.flush()
            }

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.provider",
                file
            )

            val shareSummary = "3D Box Dimension Report ($dateStr):\nL: ${String.format(Locale.US, "%.2f", length)}m, W: ${String.format(Locale.US, "%.2f", width)}m, H: ${String.format(Locale.US, "%.2f", height)}m\nVolume: ${String.format(Locale.US, "%.4f", volume)}m³"

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "3D Object Dimension Report")
                putExtra(Intent.EXTRA_TEXT, shareSummary)
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(intent, "Share 3D Report"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
